name: Docs

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
    branches: 
      - main
    types: [opened, synchronize, reopened]


concurency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ starsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - run: |
        julia --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()'
      -run: julia --project=docs -e docs/make.jl  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
